services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
#      dockerfile: Dockerfile
    image: braguru/customerservice-app:latest
    container_name: cs_backend_app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      --env-file: .env
    ports:
      - "9090:9090"
    depends_on:
      - db
    networks:
      - app-network
#    volumes:
#      - .:/app

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
