services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/app/data
    networks:
      - app-network

  app:
    image: braguru/customerservice-app:latest
    container_name: cs_backend_app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
        - ./.env
    ports:
      - "9090:9090"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - pgdata:/app/data

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
