name: Build and Push Docker Image to ECR

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

        # Check if PostgreSQL image exists
      - name: Check for existing PostgreSQL image in ECR
        id: check-postgres
        run: |
         aws ecr describe-images --repository-name $ECR_REPOSITORY_DB --image-ids imageTag=latest || echo "No PostgreSQL image found in ECR"
        continue-on-error: true

        # Build images using docker-compose
      - name: Build images with docker-compose
        run: docker-compose -f docker-compose.yml build

          # Conditionally push PostgreSQL image if it doesn't exist
      - name: Push PostgreSQL image to ECR if missing
        if: steps.check-postgres.outcome == 'failure'
        run: |
           POSTGRES_IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_DB}:latest"
           docker tag my_project_db:latest $POSTGRES_IMAGE_URI
           docker push $POSTGRES_IMAGE_URI

      - name: Delete existing image from ECR (only on main)
        if: github.ref == 'refs/heads/main'
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest"
          aws ecr batch-delete-image --repository-name $ECR_REPOSITORY --image-ids imageTag=latest || echo "Image does not exist"

#      - name: Build Docker image
#        id: build-image
#        run: |
#          docker build -t ${{ secrets.ECR_REPOSITORY }} .

      - name: Tag Docker image
        run: |
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}"
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest $IMAGE_URI:latest

      - name: Push Docker image to ECR (only on main)
        if: github.ref == 'refs/heads/main'
        run: |
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}"
          docker push $IMAGE_URI:latest
