name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      IMAGE_TAG: latest
      SHORT_SHA: ${GITHUB_SHA::7}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        id: build-image
        run: |
          docker build -t $ECR_REPOSITORY .
          echo "image built"

      - name: Tag Docker image
        run: |
          # SHORT_SHA=${GITHUB_SHA::7}
          APP_IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${SHORT_SHA}"
          docker tag $ECR_REPOSITORY:latest $APP_IMAGE_URI
          echo "Image tagged with SHA: ${SHORT_SHA}"

      - name: Push Docker image to ECR (only on main)
        if: github.ref == 'refs/heads/main'
        run: |
          APP_IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${SHORT_SHA}"
          docker push $APP_IMAGE_URI
          echo "image pushed with SHA: ${SHORT_SHA}"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            #!/bin/bash

            # Authenticate to ECR and pull the latest image
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
                    
            # Stop and remove any existing application container
            docker stop cs_backend_app || true
            docker rm cs_backend_app || true
            
            # Ensure the Docker network exists
            docker network create cs_app_network || true
            
            # Run the application container on the specified network
            docker run -d --name cs_backend_app \
              --network cs_app_network \
              --env-file cs_backend/.env \
              -p 9090:9090 \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
